### ISSUE TITLE
v1.20.0 requesting password 

### ISSUE THREAD

**Issue by EncryptedFile** [Blawuken/MicroG-Extended#1]
v1.20.0 requests a password when you open it, and there is no password listed anywhere, so I am unable to configure and utilize the latest version of this app.
Please fix ASAP!
Thank you.

//edit
![Screenshot_20240219-091022_MicroG](https://github.com/Blawuken/MicroG-Extended/assets/13071170/8c601912-f4eb-4b53-a55a-fceeabdf8ab0)

Already cleared cache/data, and attempted uninstall/reinstall, but it's still requesting a password

**Comment by Blawuken** [comment]
Password is extended
